#!/bin/bash

fail() {
   echo "Fail: " $@
   exit 1
}

test -z "$@" && fail "opus startup command needed as argument(s)"

for pid in $(pgrep -f 'ol --run opus')
do
   kill -9 $pid
   echo "Closing PID $pid"
   sleep 1
done

$@ --ephemereal -U test -P pass -p 9000 &

python test/usage.py || { kill -9 %1; exit 1; }

kill -9 %1 || true

echo "Everything seems to be in order"

exit 0

