#!/bin/bash

fail() {
   echo "Fail: " $@
   exit 1
}

mkdir -p tmp/webroot
echo "Hello, world!" > tmp/webroot/hello.txt

test -z "$@" && fail "opus startup command needed as argument(s)"

for pid in $(pgrep -f 'ol --run opus')
do
   kill -9 $pid
   echo "Closing PID $pid"
   sleep 1
done

$@ --ephemereal -U test -P pass -p 9000 --webroot tmp/webroot &

# close on errors
# python test/usage.py || { kill -9 %1; exit 1; }

# leave running
python test/usage.py || exit 1

kill -9 %1 || true

echo "Everything seems to be in order"

exit 0

