language: c

os:
  - linux

compiler:
  - clang
  - gcc

script: make verysure

before_script:
  - "sudo apt-get install python pip"
  - "sudo pip install selenium"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start
