language: c

os:
  - linux

compiler:
  - clang
  - gcc

script: make verysure

before_script:
  - "sudo apt-get install python python-pip"
  - "sudo pip install selenium"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
#  - sleep 5 # no need to sleep, because build takes a few seconds
